import React, { useState } from 'react';
import { BookOpen, Plus, Trash2, CheckCircle2, Circle, Tag, Edit3, Bookmark } from 'lucide-react';
import { NoteItem } from '../types';

interface NotesViewProps {
  notes: NoteItem[];
  onAddNote: (note: Omit<NoteItem, 'id' | 'createdAt'>) => void;
  onDeleteNote: (id: string) => void;
  onToggleComplete: (id: string) => void;
}

export const NotesView: React.FC<NotesViewProps> = ({
  notes,
  onAddNote,
  onDeleteNote,
  onToggleComplete,
}) => {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [tag, setTag] = useState<'note' | 'task' | 'snippet' | 'idea'>('note');
  const [filter, setFilter] = useState<string>('all');

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    onAddNote({
      title: title.trim(),
      content: content.trim(),
      tag,
      completed: false,
    });

    setTitle('');
    setContent('');
  };

  const filteredNotes = notes.filter((n) => {
    if (filter === 'all') return true;
    return n.tag === filter;
  });

  return (
    <div className="flex-1 flex flex-col h-full overflow-y-auto p-4 md:p-8 max-w-5xl mx-auto w-full">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center space-x-2 text-emerald-400 mb-1">
          <BookOpen className="w-5 h-5" />
          <span className="text-xs font-bold uppercase tracking-wider">LUNA WORKSPACE</span>
        </div>
        <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
          Scratchpad & Action Items
        </h1>
        <p className="text-sm text-slate-400 mt-1">
          Store ideas, code snippets, and action tasks generated by Luna during your sessions.
        </p>
      </div>

      {/* Creation form */}
      <form
        onSubmit={handleSave}
        className="luna-glass rounded-2xl p-4 md:p-5 border border-slate-800 mb-6"
      >
        <div className="flex flex-col md:flex-row gap-3 mb-3">
          <input
            type="text"
            placeholder="Title or task name..."
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="flex-1 bg-[#090f1d] border border-slate-800 rounded-xl px-3.5 py-2 text-sm text-slate-100 placeholder-slate-400 focus:outline-none focus:border-emerald-500/60"
            required
          />
          <div className="flex items-center space-x-2">
            {(['note', 'task', 'snippet', 'idea'] as const).map((t) => (
              <button
                key={t}
                type="button"
                onClick={() => setTag(t)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium uppercase tracking-wider transition-colors border ${
                  tag === t
                    ? 'bg-emerald-950/60 text-emerald-300 border-emerald-500/50'
                    : 'bg-slate-900/40 text-slate-400 border-slate-800 hover:text-slate-300'
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>

        <textarea
          rows={3}
          placeholder="Details, code snippet, or notes..."
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="w-full bg-[#090f1d] border border-slate-800 rounded-xl p-3 text-sm text-slate-200 placeholder-slate-400 focus:outline-none focus:border-emerald-500/60 resize-y mb-3 font-mono"
        />

        <div className="flex justify-end">
          <button
            type="submit"
            className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-semibold text-xs shadow-md shadow-emerald-900/30 transition-all"
          >
            <Plus className="w-4 h-4" />
            <span>Save to Scratchpad</span>
          </button>
        </div>
      </form>

      {/* Filter bar */}
      <div className="flex items-center space-x-2 mb-4">
        {['all', 'note', 'task', 'snippet', 'idea'].map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-3 py-1 rounded-lg text-xs capitalize transition-colors ${
              filter === f
                ? 'bg-slate-800 text-white font-semibold'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Notes Grid */}
      {filteredNotes.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-12 text-center text-slate-400 border border-dashed border-slate-800 rounded-2xl">
          <Bookmark className="w-10 h-10 mb-2 opacity-30" />
          <p className="text-sm font-medium">No items found</p>
          <p className="text-xs text-slate-400 mt-1">
            Capture actionable tasks and insights as you brainstorm with Luna.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pb-8">
          {filteredNotes.map((note) => (
            <div
              key={note.id}
              className={`p-4 rounded-xl luna-glass border transition-all ${
                note.completed
                  ? 'border-slate-800/60 opacity-60'
                  : 'border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex items-start justify-between gap-2 mb-2">
                <div className="flex items-center space-x-2 min-w-0">
                  {note.tag === 'task' ? (
                    <button
                      onClick={() => onToggleComplete(note.id)}
                      className="text-emerald-400 hover:text-emerald-300 mt-0.5"
                    >
                      {note.completed ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      ) : (
                        <Circle className="w-4 h-4 text-slate-400" />
                      )}
                    </button>
                  ) : (
                    <span className="w-2 h-2 rounded-full bg-emerald-400 mt-1 flex-shrink-0" />
                  )}
                  <h4
                    className={`font-semibold text-sm truncate ${
                      note.completed ? 'line-through text-slate-400' : 'text-slate-100'
                    }`}
                  >
                    {note.title}
                  </h4>
                </div>

                <div className="flex items-center space-x-1.5 flex-shrink-0">
                  <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                    {note.tag}
                  </span>
                  <button
                    onClick={() => onDeleteNote(note.id)}
                    className="p-1 hover:text-red-400 text-slate-400 rounded transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {note.content && (
                <p className="text-xs text-slate-300 whitespace-pre-wrap leading-relaxed font-mono bg-slate-950/50 p-2.5 rounded-lg border border-slate-900">
                  {note.content}
                </p>
              )}

              <div className="mt-3 text-[10px] text-slate-400">
                {new Date(note.createdAt).toLocaleDateString([], {
                  month: 'short',
                  day: 'numeric',
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
